// Generated by CoffeeScript 1.3.3
(function() {
  var Main_Controller_VM, Templates,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Templates = {
    HOME: 'home_page',
    SETTINGS: 'settings_page'
  };

  Main_Controller_VM = (function() {

    function Main_Controller_VM(inits) {
      this.Refresh_JQM = __bind(this.Refresh_JQM, this);

      this.Tap_Settings = __bind(this.Tap_Settings, this);

      this.Tap_Home = __bind(this.Tap_Home, this);

      var _this = this;
      this.template_name = ko.observable(Templates.SETTINGS);
      this.display_page = function() {
        return _this.template_name();
      };
      this.title = ko.observable("Home Testing");
      this.player_name = ko.observable("");
      this.need_help = ko.observable(false);
      this.first_player = ko.observable("");
      this.difficulty_level = ko.observable("Easy");
      this.difficulty_options = ko.observableArray(['Easy', 'Semi-Easy', 'Medium', 'Hard', 'Crazy']);
      this.settings = ko.computed(function() {
        if (!_this.player_name()) {
          return "Need to pick a name";
        } else {
          return "" + (_this.player_name()) + "\nis going " + (_this.first_player() === 'me' ? 'first' : 'second') + ",\n" + (_this.need_help() ? 'wants' : 'does not want') + " help,\nand is playing at " + (_this.difficulty_level()) + " difficulty.";
        }
      });
    }

    Main_Controller_VM.prototype.Tap_Home = function(d, e) {
      return this.template_name(Templates.HOME);
    };

    Main_Controller_VM.prototype.Tap_Settings = function(d, e) {
      return this.template_name(Templates.SETTINGS);
    };

    Main_Controller_VM.prototype.Refresh_JQM = function(d) {
      $(d).trigger("create");
    };

    return Main_Controller_VM;

  })();

  $(document).one('app_init', function(e, d) {
    var model;
    console.log("Loading Main VM");
    model = new Main_Controller_VM();
    ko.applyBindings(model);
  });

}).call(this);
